# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a7e0f9bc641072357626916613280d12291515f75faa3fab18f6d69de1644c4169c7d0f265bbc3e06312592e2dc1a6a9aef7fc7333815dffc2727ad28046359

test:
  secret_key_base: 49e231bf0f12611e4378cf2fd38c716c9b2cdeb2a5cdb6bd857146d97da4519156809dcb7db8ddfe3a79aa25eb7ba94615efa17727ae2db810a04e7f9926562e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
